[package]
name = "game"
version = "0.1.0"
authors = ["PWho <patrick@patrickwho.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
